amazon_search_product_lines = [
        "All Products",
        "Arts, Crafts &amp; Sewing",
        "Automotive",
        "Baby &amp; Nursery",
        "Beauty &amp; Grooming",
        "Blu-Ray &amp; DVD",
        "Books &amp; Textbooks",
        "Business &amp; Industrial Supplies",
        "CDs &amp; Vinyl",
        "Camera &amp; Photo",
        "Cell Phones &amp; Accessories",
        "Classical Music",
        "Clothing &amp; Accessories",
        "Collectible Coins",
        "Computers, Tablets &amp; Components",
        "Digital Music",
        "Electronic Components &amp; Home Audio",
        "Entertainment Collectibles",
        "Grocery &amp; Gourmet Food",
        "Health &amp; Household",
        "Home Improvement",
        "Jewelry",
        "Kindle Store",
        "Kitchen &amp; Dining",
        "Magazines",
        "Major Appliances",
        "Miscellaneous",
        "Musical Instruments",
        "Office &amp; School Supplies",
        "Other Gift Card Brands",
        "Patio, Lawn &amp; Garden",
        "Patio, Lawn &amp; Garden",
        "Pet Food &amp; Supplies",
        "Shoes, Handbags, Wallets, Sunglasses",
        "Software",
        "Sports &amp; Fitness",
        "Sports Collectibles",
        "Toys &amp; Games",
        "VHS",
        "Video Games",
        "Video Games",
        "Video On Demand: Rent or Buy",
        "Watches",
                     ]