from src.scripts.get_ads.get_amazon_links import store_link_for_amazon_search

async def generate_amazon_ads():
    await store_link_for_amazon_search('https://www.amazon.com/s?k=easter+candy&crid=2VD9J5L9D5F4W&sprefix=%2Caps%2C564&ref=nb_sb_ss_sx-trend-t-ps-d_3_0', 'easter candy', 'Easter-Themed Chocolate Eggs and Bunnies', 'A classic choice for Easter, these candies often come in the shape of eggs or bunnies, symbolizing new life and rebirth associated with Easter. Popular brands like Cadbury offer Easter eggs filled with creamy fondant, while others may offer solid or hollow chocolate bunnies. These treats are often used in Easter egg hunts or as basket fillers.')
    await store_link_for_amazon_search('https://www.amazon.com/s?k=easter+candy&page=2&crid=2VD9J5L9D5F4W&qid=1708854650&sprefix=%2Caps%2C564&ref=sr_pg_2', 'easter candy', 'Jelly Beans and Easter Candy Mixes', 'Jelly beans are a staple for Easter with their egg-like shape and variety of flavors. Many brands release special Easter editions with seasonal flavors and pastel colors. Candy mixes, often including a mix of jelly beans, foiled chocolate eggs, and other sweets, provide a convenient and festive option for gifting and sharing.')
    await store_link_for_amazon_search('https://www.amazon.com/s?k=easter+candy&page=2&crid=2VD9J5L9D5F4W&qid=1708854650&sprefix=%2Caps%2C564&ref=sr_pg_3', 'easter candy', 'Marshmallow Peeps', 'These are sugary, marshmallow candies shaped into various Easter-related forms like chicks and bunnies. They come in multiple colors and are a fun, playful treat for children. Peeps can be used in various creative ways, such as in baking or in crafting Easter-themed dioramas.')
    await store_link_for_amazon_search('https://www.amazon.com/s?k=easter+candy&page=2&crid=2VD9J5L9D5F4W&qid=1708854650&sprefix=%2Caps%2C564&ref=sr_pg_4', 'easter candy','Artisanal and Gourmet Easter Chocolates','For a more sophisticated palate, gourmet chocolate makers often offer artisanal Easter candy. These might include hand-painted chocolate eggs, luxury truffles with unique flavors, or organic, ethically sourced chocolate options, catering to adults and connoisseurs seeking a more refined Easter treat.')
    await store_link_for_amazon_search('https://www.amazon.com/s?k=easter+candy&page=2&crid=2VD9J5L9D5F4W&qid=1708854650&sprefix=%2Caps%2C564&ref=sr_pg_5', 'easter candy','Easter Candy Baskets and Gift Sets', 'Pre-assembled baskets featuring an assortment of Easter candies, including chocolate eggs, bunny-shaped lollipops, and marshmallow treats, make for perfect gifts. Some might also include novelty items like plush toys or Easter-themed storybooks, catering to a family-friendly holiday experience.')


    await store_link_for_amazon_search('https://www.amazon.com/s?k=water+flosser&crid=1ZP37TP8LITX5&sprefix=%2Caps%2C699&ref=nb_sb_ss_sx-trend-t-ps-d_3_0', 'water flosser', 'Cordless Water Flossers', 'Ideal for smaller bathrooms or for traveling, cordless water flossers offer the convenience of portability. They typically have a rechargeable battery and a compact design, making them easy to use without the need for a power outlet. Brands like Waterpik and Philips Sonicare offer models with various pressure settings to suit different gum sensitivities.')
    await store_link_for_amazon_search('https://www.amazon.com/s?k=water+flosser&page=2&crid=1ZP37TP8LITX5&qid=1708855262&sprefix=%2Caps%2C699&ref=sr_pg_2', 'water flosser', 'Countertop Water Flossers','These are larger and often more powerful than their cordless counterparts, suitable for a fixed place in the bathroom. They usually come with larger water reservoirs and multiple nozzle tips for different uses, such as plaque removal or periodontal pocket cleaning. The Waterpik Aquarius is a popular example, known for its multiple pressure settings and timer feature.')
    await store_link_for_amazon_search('https://www.amazon.com/s?k=water+flosser&page=2&crid=1ZP37TP8LITX5&qid=1708855262&sprefix=%2Caps%2C699&ref=sr_pg_3', 'water flosser', 'Water Flosser for Braces', 'Specialized water flosser designed for orthodontic appliances, like braces, feature tips that can navigate around wires and brackets effectively. These devices help in removing food particles and plaque from hard-to-reach areas, reducing the risk of gum disease and tooth decay during orthodontic treatment.')
    await store_link_for_amazon_search('https://www.amazon.com/s?k=water+flosser&page=2&crid=1ZP37TP8LITX5&qid=1708855262&sprefix=%2Caps%2C699&ref=sr_pg_4', 'water flosser', 'Eco-Friendly Water Flossers','For environmentally conscious consumers, there are eco-friendly options made with sustainable materials and energy-efficient designs. These models focus on minimizing water usage and maximizing cleaning efficiency, and they often come with replaceable tips to reduce waste.')
    await store_link_for_amazon_search('https://www.amazon.com/s?k=water+flosser&page=2&crid=1ZP37TP8LITX5&qid=1708855262&sprefix=%2Caps%2C699&ref=sr_pg_5', 'water flosser', 'Kids\' Water Flossers', 'Designed specifically for children, these water flossers have fun designs and are easy to use, encouraging kids to maintain good oral hygiene from a young age. They often come with colorful designs, gentle pressure settings, and are smaller in size for easy handling by young users.')


    await store_link_for_amazon_search('https://www.amazon.com/s?k=book+shelf&crid=PLRQIKRF1L2&sprefix=book%2Caps%2C1220&ref=nb_sb_ss_ts-doa-p_1_4', 'book shelf', 'Classic Wooden Book Shelf', 'Traditional wooden book shelves, like those from IKEA\'s BILLY series or Wayfair\'s collection, offer a timeless design suitable for home libraries or living rooms. They come in various sizes, from narrow single-column units to expansive multi-tiered arrangements. Features might include adjustable shelves for accommodating different book heights and optional glass doors for dust protection.')
    await store_link_for_amazon_search('https://www.amazon.com/s?k=book+shelf&page=2&crid=PLRQIKRF1L2&qid=1708855530&sprefix=book%2Caps%2C1220&ref=sr_pg_2', 'book shelf', 'Modern and Minimalist Book Shelves', 'For those with a contemporary aesthetic, brands like West Elm and CB2 offer minimalist book shelves with clean lines and modern finishes, such shelf as matte black or brushed metal. The book shelf often double as display units for decor, providing both functionality and style.')
    await store_link_for_amazon_search('https://www.amazon.com/s?k=book+shelf&page=2&crid=PLRQIKRF1L2&qid=1708855530&sprefix=book%2Caps%2C1220&ref=sr_pg_3', 'book shelf', 'Children\'s Book Shelves', 'Designed for kids\' rooms, these book shelves are often lower in height for easy access and brightly colored. Some, like the ones from Pottery Barn Kids, include themed designs or sling storage for easy visibility and reach of children\'s books. Safety features like wall anchoring and rounded edges are common.')
    await store_link_for_amazon_search('https://www.amazon.com/s?k=book+shelf&page=2&crid=PLRQIKRF1L2&qid=1708855530&sprefix=book%2Caps%2C1220&ref=sr_pg_4', 'book shelf', 'Corner Book Shelves', 'Ideal for maximizing space, corner book shelves fit snugly into room corners. Retailers like Home Depot offer various models, from ladder-style shelves to corner-specific units, which help utilize otherwise unused spaces effectively.')
    await store_link_for_amazon_search('https://www.amazon.com/s?k=book+shelf&page=2&crid=PLRQIKRF1L2&qid=1708855530&sprefix=book%2Caps%2C1220&ref=sr_pg_5', 'book shelf', 'Wall-Mounted Book Shelves', 'For those with limited floor space, wall-mounted book shelf like IKEA\'s LACK series or floating shelves offer a space-saving solution. They can be strategically placed to create a visually appealing book display and are available in various lengths and finishes.')
